# Generated by Django 5.2.7 on 2025-11-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('sellers', 'Sellers')], default='Sellers', max_length=20),
        ),
    ]
