# Generated by Django 5.2.7 on 2025-11-02 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_cpf_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve ter 11 números.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
