# Generated by Django 5.2.7 on 2025-11-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True),
        ),
    ]
