# Generated by Django 5.2.7 on 2025-11-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Porcentagem da comissão sobre o total de vendas', max_digits=5, null=True, verbose_name='Taxa de Comissão (%)'),
        ),
    ]
