# Generated by Django 5.2.7 on 2025-11-09 12:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('sales', '0002_alter_sale_date_alter_sale_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='paid',
            field=models.BooleanField(default=False, help_text='Indica se a comissão já foi paga.'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a comissão foi paga.', null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Percentual de comissão aplicado ao vendedor.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='commission',
            name='sale',
            field=models.OneToOneField(help_text='Venda associada à comissão.', on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='seller',
            field=models.ForeignKey(help_text='Vendedor responsável pela venda.', limit_choices_to={'user_type': 'sellers'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor final da comissão calculada.', max_digits=10),
        ),
    ]
