# Generated by Django 5.2.7 on 2025-11-13 01:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commission_paid_alter_commission_paid_at_and_more'),
        ('sales', '0002_alter_sale_date_alter_sale_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de comissão aplicado ao vendedor.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='commission',
            name='sale',
            field=models.OneToOneField(help_text='Venda associada à comissão.', on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='seller',
            field=models.ForeignKey(help_text='Vendedor responsável pela venda.', limit_choices_to={'user_type': 'sellers'}, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
