# Generated by Django 5.2.7 on 2025-11-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commission_percentage_alter_commission_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='seller',
        ),
    ]
