# Generated by Django 5.2.7 on 2025-11-15 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_remove_commission_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='seller',
            field=models.ForeignKey(default=1, help_text='Vendedor responsável pela venda.', limit_choices_to={'user_type': 'sellers'}, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se a comissão já foi paga.'),
        ),
    ]
