# Generated by Django 5.2.7 on 2025-11-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_alter_commission_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se a comissão já foi paga.'),
        ),
    ]
